src/objects/AM_Asset__c.object
<CustomObject>
    <fields>
        <fullName>AM_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>AM_Location__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AM_Out_of_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Out of Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AM_Status__c</fullName>
        <description>Describes the status of an asset</description>
        <formula>IF( AND(AM_Available_for_allocation__c, !AM_Out_of_Service__c ), &quot;Available&quot;, IF(  AM_Out_of_Service__c  ,&quot;Broken&quot; , &quot;Assigned&quot;))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Computer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peripherals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <picklist>
            <picklistValues>
                <fullName>Computer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iPhone headphones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Keyboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mac charger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network adapters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platronic headphones</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>AM_Asset</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AM_Location__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Paraguay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Peru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uruguay</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AM_AssetManager.cls
// @RestResource(urlMapping='/Assets/')
global with sharing class AM_AssetManager {
    AM_AssetManager() {}
	@RemoteAction
    global static String getAssets() {
        
        //Map templates
        Map<String,Object> asset = new Map<String,Object>{'asset'=>'','Assigned'=>0,'Not_Assigned'=>0,'Out_of_service'=>0};
        Map<String,Object> unassignedP = new Map<String,Object>{'asset'=>'Unassigned_Peripherals','Keyboard'=>0,'Mac charger'=>0,
            'Mouse' => 0, 'Network adapters'=>0,'Platronic headphones'=>0,'iPhone headphones'=>0};
                
        //get all assets registered     
        List<AM_Asset__c> results = [SELECT Name__c, AM_Type__c, AM_Out_of_Service__c, AM_Status__c ,AM_Location__r.Country__c FROM AM_Asset__c];
        
        //get all countries registered
        List<AM_Location__c> countries = [SELECT Country__c FROM AM_Location__c];
        
        //Map results
        Map<String,Object> country = new Map<String,Object>();
        
        for (AM_Location__c c : countries){
            
            //Initialize maps
            Map<String,Object> acomputer = new Map<string,Object>(asset);
            acomputer.put('asset', 'Computer');
            Map<String,Object> amobile = new Map<string,Object>(asset);
            amobile.put('asset', 'Mobile_Phone');
            Map<String,Object> aperipherals = new Map<string,Object>(unassignedP);
            //variables
            Integer totalc =0, totalm =0;
            for (AM_Asset__c r : results) {
                if (r.AM_Location__r.Country__c == c.Country__c) {
                    switch on r.AM_Type__c {
                        when 'Computer' {
                            totalc ++;
                            if(r.AM_Status__c == 'Assigned') { acomputer.put('Assigned',(Integer) acomputer.get('Assigned')+1); }
                            if(r.AM_Out_of_Service__c) { acomputer.put('Out_of_service',(Integer) acomputer.get('Out_of_service')+1); }
                        }
                        when 'Mobile Phone' {
                            totalm ++;
                            if(r.AM_Status__c == 'Assigned') { amobile.put('Assigned',(Integer) amobile.get('Assigned')+1); }
                            if(r.AM_Out_of_Service__c) { amobile.put('Out_of_service',(Integer) amobile.get('Out_of_service')+1); }
                        }
                        when else {
                            aperipherals.put(r.Name__c, (Integer) aperipherals.get(r.Name__c)+1);
                        }
                    }
                    
                }
            }
            acomputer.put('Not_Assigned', totalc - (Integer) acomputer.get('Assigned'));
            amobile.put('Not_Assigned', totalm - (Integer) amobile.get('Assigned'));
            country.put(c.Country__c,new List<Object>{acomputer, amobile, aperipherals});
        }
        //Log country json results
        System.debug(JSON.serialize(new Map<String,Object>{'country'=> country}));
        //return results
        RestContext.response.addHeader('Content-Type', 'application/json');
        return JSON.serialize(new Map<String,Object>{'country'=> country});
    }
}