src/objects/AM_Asset__c.object
<CustomObject>
    <fields>
        <fullName>AM_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>AM_Location__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Computer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peripherals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <picklist>
            <picklistValues>
                <fullName>Computer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iPhone headphones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Keyboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mac charger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network adapters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Platronic headphones</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>AM_Asset</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AM_Location__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Paraguay</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Peru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uruguay</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AM_AssetManagerTest.cls
@isTest
public class AM_AssetManagerTest {
	@isTest static void testGetAssets() {
        createTestRecord();
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri = 'https://cs63.lightning.force.com/services/apexrest/Assets/';
        request.httpMethod = 'GET';
        RestContext.request = request;
        // Call the method to test
        Test.startTest();
        AM_AssetManager.getAssets();
        Test.stopTest();
    }
    static void createTestRecord() {
        // Create test record
        AM_Location__c country = new AM_Location__c(Country__c ='Perú');
        insert country;
        AM_Asset__c asset = new AM_Asset__c(Name__c ='Computer', AM_Type__c='Computer', AM_Location__c=country.Id);
        insert asset;
        AM_Asset__c asset2 = new AM_Asset__c(Name__c ='Mobile Phone', AM_Type__c='Mobile Phone', AM_Location__c=country.Id);
        insert asset2;
        AM_Asset__c asset3 = new AM_Asset__c(Name__c ='Keyboard', AM_Type__c='Peripherals', AM_Location__c=country.Id);
        insert asset3;
    } 
}